### ISSUE TITLE
Can't `pip install libais` on vanilla Travis-CI

### ISSUE THREAD

**Issue by geowurster** [schwehr/libais#103]
I'm trying to build and test a library that requires libais, but when I `pip install libais` in my `.travis.yml` I get:

```console
cc1plus: error: unrecognized command line option ‘-std=c++11’
```

I got around this by installing libais before installing my own package:

```yml
language: python

python:
  - 2.7
  - 3.4

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install:
  - sudo apt-get install -qq gcc-4.8 g++-4.8
  - CC=g++-4.8 pip install libais
  - pip install -e .\[dev\]

script:
  - py.test tests --cov benthosp --cov-report term-missing
```
